"""
Reinforcement Learning Trading Environment - PPO V2 / V3

Actions:

    0 = FLAT
    1 = LONG
    2 = SHORT

The environment is designed for daily stock trading.

The agent observes technical-market features plus its current
position and chooses the target position for the next market period.

Reward design:

    portfolio return
    - transaction costs
    - drawdown penalty
    - excessive turnover penalty

The environment intentionally does NOT use future prices when
constructing the observation.
"""

# ============================================================
# IMPORTS
# ============================================================

import gymnasium as gym

from gymnasium import spaces

import numpy as np

import pandas as pd


# ============================================================
# ENVIRONMENT
# ============================================================

class StockTradingEnv(gym.Env):

    """
    PPO V2 stock trading environment.

    Actions:

        0 -> FLAT
        1 -> LONG
        2 -> SHORT

    Position values:

        -1 -> SHORT
         0 -> FLAT
        +1 -> LONG
    """

    metadata = {
        "render_modes": []
    }

    # --------------------------------------------------------
    # Technical feature columns.
    #
    # These correspond to the indicators already generated by
    # IndicatorEngine.
    # --------------------------------------------------------

    FEATURE_COLUMNS = [

        "Open",

        "High",

        "Low",

        "Close",

        "Volume",

        "EMA20",

        "EMA50",

        "EMA200",

        "RSI",

        "MACD",

        "MACD_SIGNAL",

        "MACD_HISTOGRAM",

        "BB_UPPER",

        "BB_MIDDLE",

        "BB_LOWER",

        "VWAP",

        "AVG_VOLUME",

        "ATR",

        "ADX",

        "OBV",

        "STOCH_RSI",
    ]

    # ========================================================
    # INITIALIZATION
    # ========================================================

    def __init__(
        self,
        dataframe: pd.DataFrame,
        initial_balance: float = 100000.0,
        transaction_cost: float = 0.0005,
        random_start: bool = True,
        episode_length: int = 252,
        render_mode=None,
        reward_mode="v2",
        opportunity_penalty=0.03,
        opportunity_threshold_atr=0.75,
    ):

        super().__init__()

        # ----------------------------------------------------
        # Basic configuration
        # ----------------------------------------------------

        self.initial_balance = float(
            initial_balance
        )

        self.transaction_cost = float(
            transaction_cost
        )

        self.random_start = bool(
            random_start
        )

        self.episode_length = int(
            episode_length
        )

        self.render_mode = (
            render_mode
        )

        # Reward mode:
        #   v2 = original V2 reward
        #   v3 = V2 reward + small opportunity-cost penalty
        self.reward_mode = str(reward_mode).lower().strip()
        if self.reward_mode not in {"v2", "v3"}:
            raise ValueError(
                "reward_mode must be either 'v2' or 'v3'."
            )

        self.opportunity_penalty = float(opportunity_penalty)
        self.opportunity_threshold_atr = float(opportunity_threshold_atr)

        # ----------------------------------------------------
        # Validate dataframe.
        # ----------------------------------------------------

        if dataframe is None:

            raise ValueError(
                "Dataframe cannot be None."
            )

        if dataframe.empty:

            raise ValueError(
                "Dataframe cannot be empty."
            )

        # ----------------------------------------------------
        # Copy and clean dataframe.
        # ----------------------------------------------------

        self.df = (
            dataframe
            .copy()
            .sort_index()
        )

        # ----------------------------------------------------
        # Check required columns.
        # ----------------------------------------------------

        missing_columns = [

            column

            for column in self.FEATURE_COLUMNS

            if column not in self.df.columns
        ]

        if missing_columns:

            raise ValueError(
                "Missing required RL features: "
                + ", ".join(
                    missing_columns
                )
            )

        # ----------------------------------------------------
        # Remove invalid rows.
        # ----------------------------------------------------

        self.df = (
            self.df
            .replace(
                [np.inf, -np.inf],
                np.nan,
            )
            .dropna(
                subset=self.FEATURE_COLUMNS
            )
            .copy()
        )

        if len(self.df) < 20:

            raise ValueError(
                "Not enough valid rows for RL environment."
            )

        # ----------------------------------------------------
        # Feature matrix.
        # ----------------------------------------------------

        self.feature_data = (
            self.df[
                self.FEATURE_COLUMNS
            ]
            .astype(np.float32)
            .values
        )

        # ----------------------------------------------------
        # Observation:
        #
        # 21 market/technical features
        # +
        # 1 current position
        #
        # Total = 22
        # ----------------------------------------------------

        self.observation_size = (
            len(
                self.FEATURE_COLUMNS
            )
            + 1
        )

        self.observation_space = spaces.Box(

            low=-10.0,

            high=10.0,

            shape=(
                self.observation_size,
            ),

            dtype=np.float32,
        )

        # ----------------------------------------------------
        # Action:
        #
        # 0 = FLAT
        # 1 = LONG
        # 2 = SHORT
        # ----------------------------------------------------

        self.action_space = spaces.Discrete(
            3
        )

        # ----------------------------------------------------
        # Runtime state.
        # ----------------------------------------------------

        self.current_step = 0

        self.start_step = 0

        self.end_step = (
            len(self.df) - 2
        )

        self.position = 0

        self.balance = (
            self.initial_balance
        )

        self.equity = (
            self.initial_balance
        )

        self.peak_equity = (
            self.initial_balance
        )

        self.max_drawdown = 0.0

        self.total_trades = 0

        self.total_transaction_cost = 0.0

        self.total_reward = 0.0

        self.previous_action = 0

        # ----------------------------------------------------
        # Statistics.
        # ----------------------------------------------------

        self.long_steps = 0

        self.short_steps = 0

        self.flat_steps = 0

    # ========================================================
    # NORMALIZE FEATURES
    # ========================================================

    def _normalize_features(
        self,
        row: pd.Series,
    ):

        """
        Converts raw technical features into approximately
        bounded values suitable for a neural network.

        Price and volume based features are expressed relative
        to the current closing price.

        Oscillators are already naturally bounded or are
        transformed into reasonable ranges.
        """

        close = float(
            row["Close"]
        )

        if close <= 0:

            close = 1.0

        values = []

        # ----------------------------------------------------
        # Price-relative features
        # ----------------------------------------------------

        values.append(
            0.0
        )

        values.append(
            np.clip(
                (
                    float(row["High"])
                    / close
                ) - 1.0,
                -5.0,
                5.0,
            )
        )

        values.append(
            np.clip(
                (
                    float(row["Low"])
                    / close
                ) - 1.0,
                -5.0,
                5.0,
            )
        )

        # Close itself is the reference.
        values.append(
            0.0
        )

        # ----------------------------------------------------
        # Volume
        #
        # Log scaling prevents huge raw volume values from
        # dominating the neural network.
        # ----------------------------------------------------

        volume = max(
            float(row["Volume"]),
            1.0,
        )

        avg_volume = max(
            float(row["AVG_VOLUME"]),
            1.0,
        )

        volume_ratio = (
            volume
            / avg_volume
        )

        values.append(
            np.clip(
                np.log1p(
                    volume_ratio
                ),
                -10.0,
                10.0,
            )
        )

        # ----------------------------------------------------
        # EMA relationships
        # ----------------------------------------------------

        for column in [
            "EMA20",
            "EMA50",
            "EMA200",
        ]:

            values.append(
                np.clip(
                    (
                        float(row[column])
                        / close
                    ) - 1.0,
                    -5.0,
                    5.0,
                )
            )

        # ----------------------------------------------------
        # RSI
        #
        # Convert 0-100 to approximately -1 to +1.
        # ----------------------------------------------------

        rsi = float(
            row["RSI"]
        )

        values.append(
            np.clip(
                (
                    rsi - 50.0
                ) / 50.0,
                -1.0,
                1.0,
            )
        )

        # ----------------------------------------------------
        # MACD
        # ----------------------------------------------------

        values.append(
            np.clip(
                float(
                    row["MACD"]
                ) / close,
                -1.0,
                1.0,
            )
        )

        values.append(
            np.clip(
                float(
                    row["MACD_SIGNAL"]
                ) / close,
                -1.0,
                1.0,
            )
        )

        values.append(
            np.clip(
                float(
                    row["MACD_HISTOGRAM"]
                ) / close,
                -1.0,
                1.0,
            )
        )

        # ----------------------------------------------------
        # Bollinger Bands
        # ----------------------------------------------------

        for column in [
            "BB_UPPER",
            "BB_MIDDLE",
            "BB_LOWER",
        ]:

            values.append(
                np.clip(
                    (
                        float(row[column])
                        / close
                    ) - 1.0,
                    -5.0,
                    5.0,
                )
            )

        # ----------------------------------------------------
        # VWAP
        # ----------------------------------------------------

        values.append(
            np.clip(
                (
                    float(row["VWAP"])
                    / close
                ) - 1.0,
                -5.0,
                5.0,
            )
        )

        # ----------------------------------------------------
        # Average volume
        # ----------------------------------------------------

        values.append(
            0.0
        )

        # ----------------------------------------------------
        # ATR
        # ----------------------------------------------------

        values.append(
            np.clip(
                float(
                    row["ATR"]
                ) / close,
                0.0,
                1.0,
            )
        )

        # ----------------------------------------------------
        # ADX
        #
        # ADX is generally 0-100.
        # ----------------------------------------------------

        adx = float(
            row["ADX"]
        )

        values.append(
            np.clip(
                adx / 100.0,
                0.0,
                1.0,
            )
        )

        # ----------------------------------------------------
        # OBV
        #
        # OBV is scale dependent, so use its sign.
        # ----------------------------------------------------

        obv = float(
            row["OBV"]
        )

        values.append(
            np.sign(obv)
        )

        # ----------------------------------------------------
        # Stochastic RSI
        #
        # Normally 0-1.
        # ----------------------------------------------------

        stoch_rsi = float(
            row["STOCH_RSI"]
        )

        values.append(
            np.clip(
                (
                    stoch_rsi
                    * 2.0
                ) - 1.0,
                -1.0,
                1.0,
            )
        )

        # ----------------------------------------------------
        # Current position.
        #
        # -1 = short
        #  0 = flat
        # +1 = long
        # ----------------------------------------------------

        values.append(
            float(
                self.position
            )
        )

        observation = np.asarray(
            values,
            dtype=np.float32,
        )

        # ----------------------------------------------------
        # Safety.
        # ----------------------------------------------------

        observation = np.nan_to_num(
            observation,
            nan=0.0,
            posinf=10.0,
            neginf=-10.0,
        )

        observation = np.clip(
            observation,
            -10.0,
            10.0,
        )

        return observation

    # ========================================================
    # ACTION NAME
    # ========================================================

    @staticmethod
    def action_to_position(
        action: int,
    ):

        if action == 0:

            return 0

        if action == 1:

            return 1

        if action == 2:

            return -1

        raise ValueError(
            f"Invalid action: {action}"
        )

    # ========================================================
    # ACTION LABEL
    # ========================================================

    @staticmethod
    def action_name(
        action: int,
    ):

        names = {

            0: "FLAT",

            1: "LONG",

            2: "SHORT",
        }

        return names.get(
            int(action),
            "UNKNOWN",
        )

    # ========================================================
    # POSITION LABEL
    # ========================================================

    @staticmethod
    def position_name(
        position: int,
    ):

        names = {

            -1: "SHORT",

            0: "FLAT",

            1: "LONG",
        }

        return names.get(
            int(position),
            "UNKNOWN",
        )

    # ========================================================
    # RESET
    # ========================================================

    def reset(
        self,
        *,
        seed=None,
        options=None,
    ):

        super().reset(
            seed=seed
        )

        # ----------------------------------------------------
        # Select starting point.
        # ----------------------------------------------------

        if self.random_start:

            minimum_start = 0

            maximum_start = max(
                0,
                len(self.df)
                - self.episode_length
                - 2,
            )

            if maximum_start > 0:

                self.start_step = int(
                    self.np_random.integers(
                        minimum_start,
                        maximum_start + 1,
                    )
                )

            else:

                self.start_step = 0

        else:

            self.start_step = 0

        # ----------------------------------------------------
        # Episode end.
        # ----------------------------------------------------

        self.end_step = min(

            len(self.df) - 2,

            self.start_step
            + self.episode_length,
        )

        self.current_step = (
            self.start_step
        )

        # ----------------------------------------------------
        # Portfolio state.
        # ----------------------------------------------------

        self.position = 0

        self.balance = (
            self.initial_balance
        )

        self.equity = (
            self.initial_balance
        )

        self.peak_equity = (
            self.initial_balance
        )

        self.max_drawdown = 0.0

        self.total_trades = 0

        self.total_transaction_cost = 0.0

        self.total_reward = 0.0

        self.previous_action = 0

        self.long_steps = 0

        self.short_steps = 0

        self.flat_steps = 0

        # ----------------------------------------------------
        # Initial observation.
        # ----------------------------------------------------

        row = self.df.iloc[
            self.current_step
        ]

        observation = (
            self._normalize_features(
                row
            )
        )

        info = {

            "action_name": "FLAT",

            "position": 0,

            "position_name": "FLAT",

            "current_price": float(
                row["Close"]
            ),

            "equity": self.equity,

            "drawdown": 0.0,

            "total_trades": 0,

            "transaction_cost": 0.0,

            "total_transaction_cost": 0.0,
        }

        return (
            observation,
            info,
        )

    # ========================================================
    # STEP
    # ========================================================

    def step(
        self,
        action,
    ):

        action = int(
            np.asarray(
                action
            ).item()
        )

        # ----------------------------------------------------
        # Validate action.
        # ----------------------------------------------------

        if not self.action_space.contains(
            action
        ):

            raise ValueError(
                f"Invalid action: {action}"
            )

        # ----------------------------------------------------
        # Current and next price.
        # ----------------------------------------------------

        current_row = self.df.iloc[
            self.current_step
        ]

        next_row = self.df.iloc[
            self.current_step + 1
        ]

        current_price = float(
            current_row["Close"]
        )

        next_price = float(
            next_row["Close"]
        )

        # ----------------------------------------------------
        # Convert action to target position.
        # ----------------------------------------------------

        target_position = (
            self.action_to_position(
                action
            )
        )

        previous_position = (
            self.position
        )

        # ----------------------------------------------------
        # Position change.
        #
        # LONG -> SHORT = 2 units of turnover.
        #
        # LONG -> FLAT = 1
        #
        # FLAT -> LONG = 1
        # ----------------------------------------------------

        position_change = abs(
            target_position
            - previous_position
        )

        # ----------------------------------------------------
        # Transaction cost.
        # ----------------------------------------------------

        transaction_cost = (
            position_change
            * self.transaction_cost
        )

        if position_change > 0:

            self.total_trades += 1

        self.total_transaction_cost += (
            transaction_cost
            * self.equity
        )

        # ----------------------------------------------------
        # Apply new position.
        # ----------------------------------------------------

        self.position = (
            target_position
        )

        # ----------------------------------------------------
        # Market return.
        # ----------------------------------------------------

        if current_price > 0:

            market_return = (
                next_price
                / current_price
            ) - 1.0

        else:

            market_return = 0.0

        # ----------------------------------------------------
        # Strategy return.
        #
        # LONG  -> +market return
        # FLAT  -> 0
        # SHORT -> -market return
        # ----------------------------------------------------

        strategy_return = (
            self.position
            * market_return
        )

        # ----------------------------------------------------
        # Net return.
        # ----------------------------------------------------

        net_return = (
            strategy_return
            - transaction_cost
        )

        # ----------------------------------------------------
        # Protect against impossible values.
        # ----------------------------------------------------

        net_return = float(
            np.clip(
                net_return,
                -0.99,
                10.0,
            )
        )

        # ----------------------------------------------------
        # Update equity.
        # ----------------------------------------------------

        previous_equity = (
            self.equity
        )

        self.equity = (
            self.equity
            * (
                1.0
                + net_return
            )
        )

        self.balance = (
            self.equity
        )

        # ----------------------------------------------------
        # Peak equity.
        # ----------------------------------------------------

        self.peak_equity = max(

            self.peak_equity,

            self.equity,
        )

        # ----------------------------------------------------
        # Current drawdown.
        # ----------------------------------------------------

        if self.peak_equity > 0:

            drawdown = (
                self.equity
                / self.peak_equity
            ) - 1.0

        else:

            drawdown = 0.0

        drawdown = float(
            drawdown
        )

        self.max_drawdown = min(

            self.max_drawdown,

            drawdown,
        )

        # ----------------------------------------------------
        # Reward.
        #
        # Base:
        #     logarithmic portfolio growth
        #
        # Penalties:
        #     drawdown
        #     turnover
        #
        # The transaction cost has already affected equity,
        # so the turnover penalty is deliberately small.
        # ----------------------------------------------------

        equity_growth = (
            self.equity
            / max(
                previous_equity,
                1e-8,
            )
        )

        equity_growth = max(
            equity_growth,
            1e-8,
        )

        log_return = float(
            np.log(
                equity_growth
            )
        )

        drawdown_penalty = (
            0.05
            * abs(
                min(
                    drawdown,
                    0.0,
                )
            )
        )

        turnover_penalty = (
            0.01
            * position_change
            * self.transaction_cost
        )

        # ----------------------------------------------------
        # V3 opportunity-cost penalty.
        #
        # V2 had no explicit penalty for staying FLAT during
        # a strong directional move. That can create a trivial
        # low-risk policy: remain in cash almost all the time.
        #
        # V3 adds a SMALL penalty only when: ''' + '''
        #   1. the agent is FLAT, and
        #   2. the next-bar move is large relative to ATR.
        #
        # This does NOT force trading. It simply tells PPO that
        # missing unusually large opportunities has a cost.
        # ----------------------------------------------------
        opportunity_penalty = 0.0

        if self.reward_mode == "v3" and self.position == 0:

            atr = max(
                float(current_row["ATR"]),
                1e-8,
            )

            atr_fraction = atr / max(current_price, 1e-8)

            move_strength = abs(market_return) / max(
                atr_fraction,
                1e-8,
            )

            if move_strength > self.opportunity_threshold_atr:

                excess_strength = min(
                    move_strength - self.opportunity_threshold_atr,
                    2.0,
                )

                opportunity_penalty = (
                    self.opportunity_penalty
                    * excess_strength
                )

        reward = (
            log_return
            - drawdown_penalty
            - turnover_penalty
            - opportunity_penalty
        )

        reward = float(
            np.clip(
                reward,
                -10.0,
                10.0,
            )
        )

        self.total_reward += (
            reward
        )

        # ----------------------------------------------------
        # Exposure statistics.
        # ----------------------------------------------------

        if self.position == 1:

            self.long_steps += 1

        elif self.position == -1:

            self.short_steps += 1

        else:

            self.flat_steps += 1

        # ----------------------------------------------------
        # Move forward.
        # ----------------------------------------------------

        self.current_step += 1

        # ----------------------------------------------------
        # Determine termination.
        # ----------------------------------------------------

        terminated = (
            self.current_step
            >= self.end_step
        )

        truncated = False

        # ----------------------------------------------------
        # Next observation.
        # ----------------------------------------------------

        next_row_for_observation = (
            self.df.iloc[
                min(
                    self.current_step,
                    len(self.df) - 1,
                )
            ]
        )

        observation = (
            self._normalize_features(
                next_row_for_observation
            )
        )

        # ----------------------------------------------------
        # Info dictionary.
        # ----------------------------------------------------

        info = {

            "action": action,

            "action_name": (
                self.action_name(
                    action
                )
            ),

            "position": (
                self.position
            ),

            "position_name": (
                self.position_name(
                    self.position
                )
            ),

            "previous_position": (
                previous_position
            ),

            "current_price": (
                current_price
            ),

            "next_price": (
                next_price
            ),

            "market_return": (
                float(
                    market_return
                )
            ),

            "strategy_return": (
                float(
                    strategy_return
                )
            ),

            "transaction_cost": (
                float(
                    transaction_cost
                )
            ),

            "net_return": (
                float(
                    net_return
                )
            ),

            "reward": (
                reward
            ),

            "reward_mode": self.reward_mode,

            "opportunity_penalty": float(
                opportunity_penalty
            ),

            "equity": (
                float(
                    self.equity
                )
            ),

            "drawdown": (
                float(
                    drawdown
                )
            ),

            "max_drawdown": (
                float(
                    self.max_drawdown
                )
            ),

            "total_trades": (
                self.total_trades
            ),

            "total_transaction_cost": (
                float(
                    self.total_transaction_cost
                )
            ),

            "total_reward": (
                float(
                    self.total_reward
                )
            ),

            "current_step": (
                self.current_step
            ),
        }

        return (

            observation,

            reward,

            terminated,

            truncated,

            info,
        )

    # ========================================================
    # RENDER
    # ========================================================

    def render(
        self,
    ):

        print(
            f"Step: {self.current_step} | "
            f"Position: "
            f"{self.position_name(self.position)} | "
            f"Equity: ₹{self.equity:,.2f} | "
            f"Trades: {self.total_trades}"
        )

    # ========================================================
    # CLOSE
    # ========================================================

    def close(
        self,
    ):

        pass