import os
import pandas as pd
import streamlit as st


# ============================================================
# PAGE CONFIG
# ============================================================

st.set_page_config(
    page_title="Backtesting",
    page_icon="🧪",
    layout="wide",
)


# ============================================================
# PATHS
# ============================================================

PROJECT_ROOT = os.path.dirname(
    os.path.dirname(os.path.abspath(__file__))
)

RESULTS_DIR = os.path.join(
    PROJECT_ROOT,
    "models",
    "hybrid_v6_backtest",
)

RESULTS_FILE = os.path.join(
    RESULTS_DIR,
    "hybrid_v6_results.csv",
)

AGGREGATE_FILE = os.path.join(
    RESULTS_DIR,
    "hybrid_v6_aggregate.csv",
)


# ============================================================
# HEADER
# ============================================================

st.title("🧪 Backtesting")

st.caption(
    "Historical validation of Buy & Hold, Technical and Hybrid PPO V6 strategies."
)

st.divider()


# ============================================================
# EXPLANATION
# ============================================================

st.info(
    """
    **Hybrid PPO V6 Backtest**

    This page displays results generated by the actual Stock Assistant
    backtesting engine.

    Strategies compared:

    • Buy & Hold
    • Existing Technical Signal
    • Quant + Technical + PPO V6

    ⚠️ Backtest results do not guarantee future performance.
    """
)


# ============================================================
# CHECK RESULTS
# ============================================================

if not os.path.exists(RESULTS_FILE):

    st.error(
        "Backtest results were not found."
    )

    st.code(
        "python rl\\backtest_hybrid_v6.py"
    )

    st.stop()


# ============================================================
# LOAD DATA
# ============================================================

try:

    results_df = pd.read_csv(
        RESULTS_FILE
    )

except Exception as e:

    st.error(
        f"Unable to load backtest results: {e}"
    )

    st.stop()


aggregate_df = None

if os.path.exists(AGGREGATE_FILE):

    try:

        aggregate_df = pd.read_csv(
            AGGREGATE_FILE
        )

    except Exception:
        aggregate_df = None


# ============================================================
# CLEAN COLUMN NAMES
# ============================================================

results_df.columns = [
    str(c).strip()
    for c in results_df.columns
]

if aggregate_df is not None:

    aggregate_df.columns = [
        str(c).strip()
        for c in aggregate_df.columns
    ]


# ============================================================
# OVERVIEW
# ============================================================

st.subheader("📊 Backtest Overview")


col1, col2, col3, col4 = st.columns(4)


with col1:

    st.metric(
        "Stocks Tested",
        results_df["ticker"].nunique()
        if "ticker" in results_df.columns
        else len(results_df),
    )


with col2:

    st.metric(
        "Strategies",
        results_df["strategy"].nunique()
        if "strategy" in results_df.columns
        else 0,
    )


with col3:

    st.metric(
        "Initial Capital",
        "₹100,000",
    )


with col4:

    st.metric(
        "Transaction Cost",
        "0.050%",
    )


st.divider()


# ============================================================
# AGGREGATE RESULTS
# ============================================================

st.subheader("🏆 Strategy Comparison")


if aggregate_df is not None and not aggregate_df.empty:

    display_df = aggregate_df.copy()

    # Make column names readable
    rename_map = {
        "strategy": "Strategy",
        "stocks": "Stocks",
        "mean_return": "Mean Return",
        "median_return": "Median Return",
        "mean_sharpe": "Mean Sharpe",
        "mean_max_drawdown": "Mean Max Drawdown",
        "mean_trades": "Mean Trades",
    }

    display_df = display_df.rename(
        columns=rename_map
    )

    st.dataframe(
        display_df,
        use_container_width=True,
        hide_index=True,
    )

else:

    st.warning(
        "Aggregate results file is unavailable."
    )


# ============================================================
# PERFORMANCE HIGHLIGHTS
# ============================================================

st.divider()

st.subheader("📈 Performance Highlights")


if aggregate_df is not None and not aggregate_df.empty:

    # Convert percentages stored as strings such as "4.01%"
    def percentage_to_float(value):

        try:

            value = float(
                str(value)
                .replace("%", "")
                .strip()
            )

            return value * 100

        except Exception:

            return None


    if "mean_return" in aggregate_df.columns:

        returns = aggregate_df.copy()

        returns["_return_numeric"] = (
            returns["mean_return"]
            .apply(percentage_to_float)
        )

        returns = returns.dropna(
            subset=["_return_numeric"]
        )

        if not returns.empty:

            best_row = returns.loc[
                returns["_return_numeric"].idxmax()
            ]

            best_strategy = best_row["strategy"]
            best_return = (
                percentage_to_float(
                    best_row["mean_return"]
                )
            )

            best_return = (
                f"{best_return:.2f}%"
                if best_return is not None
                else "N/A"
            )

        else:

            best_strategy = "N/A"
            best_return = "N/A"

    else:

        best_strategy = "N/A"
        best_return = "N/A"


    if "mean_sharpe" in aggregate_df.columns:

        sharpe_values = pd.to_numeric(
            aggregate_df["mean_sharpe"],
            errors="coerce",
        )

        if sharpe_values.notna().any():

            best_sharpe_index = sharpe_values.idxmax()

            best_sharpe_strategy = aggregate_df.loc[
                best_sharpe_index,
                "strategy",
            ]

            best_sharpe = aggregate_df.loc[
                best_sharpe_index,
                "mean_sharpe",
            ]

        else:

            best_sharpe_strategy = "N/A"
            best_sharpe = "N/A"

    else:

        best_sharpe_strategy = "N/A"
        best_sharpe = "N/A"


    c1, c2, c3 = st.columns(3)


    with c1:

        st.metric(
            "Best Mean Return",
            str(best_return),
            help=f"Strategy: {best_strategy}",
        )


    with c2:

        st.metric(
            "Best Mean Sharpe",
            str(best_sharpe),
            help=f"Strategy: {best_sharpe_strategy}",
        )


    with c3:

        st.metric(
            "Best Strategy",
            str(best_strategy),
        )


# ============================================================
# STOCK LEVEL RESULTS
# ============================================================

st.divider()

st.subheader("📋 Stock-Level Results")


if "ticker" in results_df.columns:

    tickers = sorted(
        results_df["ticker"]
        .dropna()
        .astype(str)
        .unique()
        .tolist()
    )

    selected_ticker = st.selectbox(
        "Select Stock",
        tickers,
    )

    stock_df = results_df[
        results_df["ticker"].astype(str)
        == selected_ticker
    ].copy()

    st.dataframe(
        stock_df,
        use_container_width=True,
        hide_index=True,
    )

else:

    st.dataframe(
        results_df,
        use_container_width=True,
        hide_index=True,
    )


# ============================================================
# STRATEGY FILTER
# ============================================================

st.divider()

st.subheader("🔎 Strategy Analysis")


if "strategy" in results_df.columns:

    strategies = sorted(
        results_df["strategy"]
        .dropna()
        .astype(str)
        .unique()
        .tolist()
    )

    selected_strategy = st.selectbox(
        "Select Strategy",
        strategies,
    )

    strategy_df = results_df[
        results_df["strategy"].astype(str)
        == selected_strategy
    ].copy()


    # --------------------------------------------------------
    # Strategy metrics
    # --------------------------------------------------------

    c1, c2, c3, c4 = st.columns(4)


    def numeric_column(
        dataframe,
        names,
    ):

        for name in names:

            if name in dataframe.columns:

                return pd.to_numeric(
                    dataframe[name],
                    errors="coerce",
                )

        return pd.Series(dtype=float)


    returns = numeric_column(
        strategy_df,
        [
            "return",
            "total_return",
            "Return",
        ],
    )


    sharpe = numeric_column(
        strategy_df,
        [
            "sharpe",
            "Sharpe",
        ],
    )


    drawdown = numeric_column(
        strategy_df,
        [
            "max_drawdown",
            "Max DD",
            "max_dd",
        ],
    )


    trades = numeric_column(
        strategy_df,
        [
            "trades",
            "Trades",
        ],
    )


    with c1:

        if not returns.empty:

            st.metric(
                "Average Return",
                f"{returns.mean() * 100:.2f}%",
            )

        else:

            st.metric(
                "Average Return",
                "N/A",
            )


    with c2:

        if not sharpe.empty:

            st.metric(
                "Average Sharpe",
                f"{sharpe.mean():.3f}",
            )

        else:

            st.metric(
                "Average Sharpe",
                "N/A",
            )


    with c3:

        if not drawdown.empty:

            st.metric(
                "Average Max DD",
                f"{drawdown.mean() * 100:.2f}%",
            )

        else:

            st.metric(
                "Average Max DD",
                "N/A",
            )


    with c4:

        if not trades.empty:

            st.metric(
                "Average Trades",
                f"{trades.mean():.1f}",
            )

        else:

            st.metric(
                "Average Trades",
                "N/A",
            )


# ============================================================
# RETURN CHART
# ============================================================

st.divider()

st.subheader("📊 Return Comparison")


if (
    aggregate_df is not None
    and not aggregate_df.empty
    and "strategy" in aggregate_df.columns
    and "mean_return" in aggregate_df.columns
):

    chart_df = aggregate_df[
        [
            "strategy",
            "mean_return",
        ]
    ].copy()


    def convert_return(value):

        try:

            return float(
                str(value)
                .replace("%", "")
                .strip()
            )

        except Exception:

            return 0.0


    chart_df["mean_return_numeric"] = (
        chart_df["mean_return"]
        .apply(convert_return)
        * 100
    )


    chart_df = chart_df.set_index(
        "strategy"
    )


    st.bar_chart(
        chart_df[
            "mean_return_numeric"
        ]
    )

    st.caption(
        "Mean return (%)"
    )


# ============================================================
# INTERPRETATION
# ============================================================

st.divider()

st.subheader("🧠 Interpretation")


st.write(
    """
    The backtest should be interpreted as a research tool rather than
    proof of profitability.

    **Buy & Hold** provides a passive benchmark.

    **Technical** represents the existing rule-based signal engine.

    **Hybrid V6** combines the quantitative score, technical analysis
    and PPO V6 reinforcement-learning position.

    The important comparison is whether Hybrid V6 improves the
    risk-adjusted results of the existing technical strategy.
    """
)


# ============================================================
# PROJECT STATUS
# ============================================================

st.divider()

st.success(
    """
    ✅ **Backtesting engine connected**

    Historical results generated by the Stock Assistant backtesting
    engine are now available inside the dashboard.
    """
)


st.caption(
    "Educational / Research Use Only — Backtests do not guarantee future performance."
)